version: "3.5"

services:
  demo-jenkins:
    image: frontend
    # container_name: veo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
# run multi env with file docker
# docker-compose -f docker-compose-prod.yml up -d --build

#run with env production
# docker build -f Dockerfile-prod -t veo-frontend-prod .
#  docker run -it -p 80:80 --rm veo-frontend
